version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok_tunnel
    environment:
      - NGROK_AUTHTOKEN=2mxgQq7VxFzCpM3PlQ13tNz9Pa0_6gfJJMuqM2KcJbxyFRaCb
    command: http 80 --url=model-recently-chipmunk.ngrok-free.app
    depends_on:
      - nginx
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
