---
- name: Copy Dockerfile to Jenkins Server
  hosts: jenkins
  become: yes
  tasks:
    - name: Copy Dockerfile from local machine to remote server
      copy:
        src: Dockerfile
        dest: /home/ec2-user/Dockerfile

    - name: Ensure Jenkins service is started
      systemd:
        name: jenkins
        state: started
        enabled: yes
